# Generated by Django 4.2.7 on 2025-06-27 11:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('motto', models.CharField(blank=True, help_text='길드 모토', max_length=200)),
                ('max_members', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(8)])),
                ('is_private', models.BooleanField(default=False, help_text='비공개 길드 여부')),
                ('join_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('total_quests_completed', models.PositiveIntegerField(default=0)),
                ('emblem', models.CharField(default='shield', max_length=50)),
                ('color_theme', models.CharField(default='#3B82F6', help_text='HEX 색상 코드', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '길드',
                'verbose_name_plural': '길드들',
                'db_table': 'guilds',
            },
        ),
        migrations.CreateModel(
            name='GuildQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_type', models.CharField(choices=[('total_quests', '총 퀘스트 완료 수'), ('member_participation', '멤버 참여율'), ('streak_days', '연속 완료 일수'), ('stat_improvement', '스탯 향상')], max_length=20)),
                ('target_value', models.PositiveIntegerField()),
                ('current_progress', models.PositiveIntegerField(default=0)),
                ('reward_guild_experience', models.PositiveIntegerField(default=0)),
                ('reward_member_experience', models.PositiveIntegerField(default=0)),
                ('reward_member_gold', models.PositiveIntegerField(default=0)),
                ('reward_member_gems', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', '진행 중'), ('completed', '완료'), ('failed', '실패'), ('expired', '만료')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_quests', to='guilds.guild')),
            ],
            options={
                'verbose_name': '길드 퀘스트',
                'verbose_name_plural': '길드 퀘스트들',
                'db_table': 'guild_quests',
            },
        ),
        migrations.CreateModel(
            name='GuildMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('general', '일반'), ('encouragement', '응원'), ('celebration', '축하'), ('quest_share', '퀘스트 공유')], default='general', max_length=20)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='guilds.guild')),
                ('recipient', models.ForeignKey(blank=True, help_text='특정 멤버에게 보내는 메시지, 없으면 전체 메시지', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_guild_messages', to=settings.AUTH_USER_MODEL)),
                ('related_quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guild_messages', to='quests.quest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '길드 메시지',
                'verbose_name_plural': '길드 메시지들',
                'db_table': 'guild_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuildRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.CharField(choices=[('weekly', '주간'), ('monthly', '월간'), ('all_time', '전체')], max_length=20)),
                ('rank_position', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField(help_text='랭킹 점수')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guild')),
            ],
            options={
                'verbose_name': '길드 랭킹',
                'verbose_name_plural': '길드 랭킹들',
                'db_table': 'guild_rankings',
                'ordering': ['rank_position'],
                'unique_together': {('guild', 'ranking_type', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='GuildMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', '길드장'), ('officer', '부길드장'), ('member', '일반 멤버')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', '활성'), ('inactive', '비활성'), ('left', '탈퇴'), ('kicked', '추방')], default='active', max_length=20)),
                ('contributed_experience', models.PositiveIntegerField(default=0)),
                ('quests_completed', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='guilds.guild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '길드 멤버십',
                'verbose_name_plural': '길드 멤버십들',
                'db_table': 'guild_memberships',
                'unique_together': {('guild', 'user')},
            },
        ),
    ]
