version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: healthquest
      POSTGRES_USER: healthquest
      POSTGRES_PASSWORD: healthquest123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py setup_dev && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://healthquest:healthquest123@db:5432/healthquest
      - REDIS_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A healthquest worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://healthquest:healthquest123@db:5432/healthquest
      - REDIS_URL=redis://redis:6379/0

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - NODE_ENV=development
    depends_on:
      - web

volumes:
  postgres_data:
  redis_data: