# Generated by Django 4.2.7 on 2025-06-27 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='trophy', max_length=50)),
                ('category', models.CharField(choices=[('quest', '퀘스트'), ('stats', '스탯'), ('social', '소셜'), ('special', '특별')], default='quest', max_length=20)),
                ('requirement_type', models.CharField(choices=[('quest_count', '퀘스트 완료 수'), ('streak', '연속 완료'), ('stat_level', '스탯 레벨'), ('level', '캐릭터 레벨'), ('special', '특별 조건')], max_length=20)),
                ('requirement_value', models.PositiveIntegerField()),
                ('reward_gold', models.PositiveIntegerField(default=0)),
                ('reward_gems', models.PositiveIntegerField(default=0)),
                ('reward_experience', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '업적',
                'verbose_name_plural': '업적들',
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='캐릭터 이름', max_length=50)),
                ('level', models.PositiveIntegerField(default=1)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('stamina', models.PositiveIntegerField(default=10, help_text='체력 - 기초 체력, 에너지 관리')),
                ('strength', models.PositiveIntegerField(default=10, help_text='근력 - 근육 운동, 저항 운동')),
                ('mental', models.PositiveIntegerField(default=10, help_text='정신력 - 스트레스 관리, 집중력')),
                ('endurance', models.PositiveIntegerField(default=10, help_text='지구력 - 유산소, 지속력')),
                ('cardio', models.PositiveIntegerField(default=10, help_text='심폐 - 심혈관 건강')),
                ('flexibility', models.PositiveIntegerField(default=10, help_text='유연성 - 스트레칭, 요가')),
                ('nutrition', models.PositiveIntegerField(default=10, help_text='영양 - 균형잡힌 식단')),
                ('recovery', models.PositiveIntegerField(default=10, help_text='회복 - 수면, 휴식')),
                ('gold', models.PositiveIntegerField(default=100)),
                ('gems', models.PositiveIntegerField(default=0)),
                ('skin', models.CharField(default='default', help_text='캐릭터 스킨', max_length=50)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '캐릭터',
                'verbose_name_plural': '캐릭터들',
                'db_table': 'characters',
            },
        ),
        migrations.CreateModel(
            name='StatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('stamina', '체력'), ('strength', '근력'), ('mental', '정신력'), ('endurance', '지구력'), ('cardio', '심폐'), ('flexibility', '유연성'), ('nutrition', '영양'), ('recovery', '회복')], max_length=20)),
                ('old_value', models.PositiveIntegerField()),
                ('new_value', models.PositiveIntegerField()),
                ('change_reason', models.CharField(help_text='변화 사유', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_history', to='characters.character')),
            ],
            options={
                'verbose_name': '스탯 변화 기록',
                'verbose_name_plural': '스탯 변화 기록들',
                'db_table': 'stat_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=True, help_text='프로필에 표시 여부')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 업적',
                'verbose_name_plural': '사용자 업적들',
                'db_table': 'user_achievements',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
